name: Build & Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t my-backend ./backend